Feat/add custom dapr components
whiteducksoftware/dapr-demo pull request #5
Opened 2021-04-30 07:38 UTC by m-voit

## Describe your Pull Request
- Add custom dapr components to use different state store and pubsub components depending on the environment (e.g cloud or local).
- Add pwsh scripts to start daprized services with cloud or local components.
- Align naming of dapr components and daprized apps.

Fixes # (issue)

Please select relevant options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

2021-04-30 09:22 UTC, mjisaak requested changes
Sieht gut aus!

2021-04-30 09:22 UTC, mjisaak commented on services/client/main.go
> +		Data:        []byte(`{ "Id": 1, "Name": "Nico" }`),
Ich würde den Namen Fred Duck und John Doe bevorzugen allerdings sollten wir die variablen (nico und martin) ändern

2021-04-30 09:22 UTC, mjisaak commented on services/messageservice/Services/MessageService.cs
> +        public const string StoreName = "dapr-demo-state-store";
Sehr schön, dass Du die Komponenten umbenannt hast

2021-04-30 14:06 UTC, m-voit commented on services/client/main.go
> +		Data:        []byte(`{ "Id": 1, "Name": "Nico" }`),
Alles klar, ich habe die Namen und die Variablen entsprechend angepasst.

2021-05-02 15:47 UTC, mjisaak approved these changes

2021-05-03 11:11 UTC, merged